jwt:
  secret: '9a02115a835ee03d5fb83cd8a468ea33e4090aaaec87f53c9fa54512bbef4db8dc656c82a315fa0c785c08b0134716b81ddcd0153d2a7556f2e154912cf5675f'


server:
  port: 8081
  error:
    whitelabel:
      enabled: false # This is the better way to handle the page not found page.

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal
    username: root
    password: material4u@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# The config below is how we override the default spring spring boot whitelabel error
#  page when we try to access a page that doesn't exist.

# This approach is not the best because the class we are disabling has
# a lot of other functions in it and must times our application might need those

#  mvc:
#    throw-exception-if-no-handler-found: true
#  web:
#    resources:
#      add-mappings: false